Dealing with money by adding currency.js
Butterfingers-2011/MyTab pull request #137
Opened 2021-02-07 00:25 UTC by ahillary

* [ ] added dependency currency.js so deal with currency in our database
* [ ] models user_group and expense deal with FLOAT, not INTEGER
* [ ] database now able to store dollars and cents instead of all pennies
* [ ] refactored groups api to reflect use of currency
* [ ] added note in groups api for a reminder to later add a validation
* [ ] moved dummydata to script file
* [ ] update dummydata to have decimals again
* [ ] update dummydata for user passwords to be password to more easily test as engineers (left two of them with secure passwords)
* [ ] CreateGroupExpenseForm refactored state with defaultState for less lines of total code in file
* [ ] CreateGroupExpenseForm added try/catch
* [ ] CreateGroupExpenseForm used currency.js for incoming data
* [ ] GroupExpenses added currency.js for rendering
* [ ] SingleExpense added currency.js for rendering

2021-02-07 00:31 UTC, ahillary commented
Also added api deletion of friend going both ways

2021-02-08 17:30 UTC, saba-mo commented on client/components/expenses/CreateGroupExpenseForm.js
> +    addGroupExpense: (groupId, newExpenseName, newExpenseCost) =>
superfluous code

2021-02-08 17:33 UTC, saba-mo requested changes
see comment

2021-02-08 17:35 UTC, saba-mo approved these changes

2021-02-08 17:35 UTC, merged